apiVersion: v1
kind: Secret
metadata:
   name: aws-secret
data:
   aws_secret_access_key: aStZQUVXa3UxSER2OWoxVzMyWVBNNmhPbXpweGRUKzY2TS9EN05GUw==
   aws_access_key: L3V6bnlrVFFRUnVnbHBNTEw4RDdQWmxzaW5SVFkwQzAvcW84Y2ErVw==