version: "3"
services:
  reverseproxy:
      image: reverseproxy:v8
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user:v8
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres' 
      POSTGRES_HOST: 'database-1.cpz8hh4xihsr.us-east-1.rds.amazonaws.com'
      AWS_REGION: 'us-east-1' 
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'test-7888585581-bucket'
      JWT_SECRET: 'test'
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed:v8
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres' 
      POSTGRES_HOST: 'database-1.cpz8hh4xihsr.us-east-1.rds.amazonaws.com'
      AWS_REGION: 'us-east-1' 
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'test-7888585581-bucket'
      JWT_SECRET: 'test'
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:v8
    ports:
      - "8100:80"
  