version: "3"
services:
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres' 
      POSTGRES_HOST: 'database-1.cpz8hh4xihsr.us-east-1.rds.amazonaws.com'
      AWS_REGION: 'us-east-1' 
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'tesr-7888585581-dev'
      JWT_SECRET: 'test'
      URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres' 
      POSTGRES_HOST: 'database-1.cpz8hh4xihsr.us-east-1.rds.amazonaws.com'
      AWS_REGION: 'us-east-1' 
      AWS_PROFILE: 'default' 
      AWS_BUCKET: 'tesr-7888585581-dev'
      JWT_SECRET: 'test'
      URL: "http://localhost:8100"
  